# Generated by Django 5.2.15 on 2026-10-02 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def validate_existing_payments(apps, schema_editor):
    payment = apps.get_model("payments", "Payment")
    invalid_payments = payment.objects.using(schema_editor.connection.alias).filter(
        models.Q(amount__lte=0) | ~models.Q(payment_method__in=["CASH", "YAPE_PLIN"])
    )
    if invalid_payments.exists():
        raise RuntimeError(
            "Payments migration stopped: non-positive amounts or unsupported payment methods exist. Review these records manually before deploying."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(validate_existing_payments, migrations.RunPython.noop),
        migrations.AddField(
            model_name="payment",
            name="idempotency_key",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="request_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="payment",
            name="void_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="payment",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="voided_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("YAPE_PLIN", "Yape/Plin")], max_length=50
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
    ]
